# prod
FROM node as builder
WORKDIR /app
COPY package*.json ./

RUN yarn install

COPY . .
RUN yarn run build

FROM node
WORKDIR /app
COPY package*.json ./

RUN yarn install --production=true
COPY --from=builder /app/build ./build

EXPOSE 8000
CMD [ "node", "build/app.js" ]
